class AddMultipleRests < ActiveRecord::Migration
  def change

	  add_column :past_teams, :zero_zero_ortg, :float
	  add_column :past_teams, :zero_zero_drtg, :float
	  add_column :past_teams, :zero_zero_poss, :float
	  add_column :past_teams, :zero_zero_games, :integer
	  add_column :past_teams, :zero_one_ortg, :float
	  add_column :past_teams, :zero_one_drtg, :float
	  add_column :past_teams, :zero_one_poss, :float
	  add_column :past_teams, :zero_one_games, :integer
	  add_column :past_teams, :zero_two_ortg, :float
	  add_column :past_teams, :zero_two_drtg, :float
	  add_column :past_teams, :zero_two_poss, :float
	  add_column :past_teams, :zero_two_games, :integer
	  add_column :past_teams, :zero_three_ortg, :float
	  add_column :past_teams, :zero_three_drtg, :float
	  add_column :past_teams, :zero_three_poss, :float
	  add_column :past_teams, :zero_three_games, :integer

	  add_column :past_teams, :one_zero_ortg, :float
	  add_column :past_teams, :one_zero_drtg, :float
	  add_column :past_teams, :one_zero_poss, :float
	  add_column :past_teams, :one_zero_games, :integer
	  add_column :past_teams, :one_one_ortg, :float
	  add_column :past_teams, :one_one_drtg, :float
	  add_column :past_teams, :one_one_poss, :float
	  add_column :past_teams, :one_one_games, :integer
	  add_column :past_teams, :one_two_ortg, :float
	  add_column :past_teams, :one_two_drtg, :float
	  add_column :past_teams, :one_two_poss, :float
	  add_column :past_teams, :one_two_games, :integer
	  add_column :past_teams, :one_three_ortg, :float
	  add_column :past_teams, :one_three_drtg, :float
	  add_column :past_teams, :one_three_poss, :float
	  add_column :past_teams, :one_three_games, :integer

	  add_column :past_teams, :two_zero_ortg, :float
	  add_column :past_teams, :two_zero_drtg, :float
	  add_column :past_teams, :two_zero_poss, :float
	  add_column :past_teams, :two_zero_games, :integer
	  add_column :past_teams, :two_one_ortg, :float
	  add_column :past_teams, :two_one_drtg, :float
	  add_column :past_teams, :two_one_poss, :float
	  add_column :past_teams, :two_one_games, :integer
	  add_column :past_teams, :two_two_ortg, :float
	  add_column :past_teams, :two_two_drtg, :float
	  add_column :past_teams, :two_two_poss, :float
	  add_column :past_teams, :two_two_games, :integer
	  add_column :past_teams, :two_three_ortg, :float
	  add_column :past_teams, :two_three_drtg, :float
	  add_column :past_teams, :two_three_poss, :float
	  add_column :past_teams, :two_three_games, :integer

	  add_column :past_teams, :three_zero_ortg, :float
	  add_column :past_teams, :three_zero_drtg, :float
	  add_column :past_teams, :three_zero_poss, :float
	  add_column :past_teams, :three_zero_games, :integer
	  add_column :past_teams, :three_one_ortg, :float
	  add_column :past_teams, :three_one_drtg, :float
	  add_column :past_teams, :three_one_poss, :float
	  add_column :past_teams, :three_one_games, :integer
	  add_column :past_teams, :three_two_ortg, :float
	  add_column :past_teams, :three_two_drtg, :float
	  add_column :past_teams, :three_two_poss, :float
	  add_column :past_teams, :three_two_games, :integer
	  add_column :past_teams, :three_three_ortg, :float
	  add_column :past_teams, :three_three_drtg, :float
	  add_column :past_teams, :three_three_poss, :float
	  add_column :past_teams, :three_three_games, :integer

	  add_column :seasons, :zero_zero_ortg, :float
	  add_column :seasons, :zero_zero_drtg, :float
	  add_column :seasons, :zero_zero_poss, :float
	  add_column :seasons, :zero_zero_games, :integer
	  add_column :seasons, :zero_one_ortg, :float
	  add_column :seasons, :zero_one_drtg, :float
	  add_column :seasons, :zero_one_poss, :float
	  add_column :seasons, :zero_one_games, :integer
	  add_column :seasons, :zero_two_ortg, :float
	  add_column :seasons, :zero_two_drtg, :float
	  add_column :seasons, :zero_two_poss, :float
	  add_column :seasons, :zero_two_games, :integer
	  add_column :seasons, :zero_three_ortg, :float
	  add_column :seasons, :zero_three_drtg, :float
	  add_column :seasons, :zero_three_poss, :float
	  add_column :seasons, :zero_three_games, :integer

	  add_column :seasons, :one_zero_ortg, :float
	  add_column :seasons, :one_zero_drtg, :float
	  add_column :seasons, :one_zero_poss, :float
	  add_column :seasons, :one_zero_games, :integer
	  add_column :seasons, :one_one_ortg, :float
	  add_column :seasons, :one_one_drtg, :float
	  add_column :seasons, :one_one_poss, :float
	  add_column :seasons, :one_one_games, :integer
	  add_column :seasons, :one_two_ortg, :float
	  add_column :seasons, :one_two_drtg, :float
	  add_column :seasons, :one_two_poss, :float
	  add_column :seasons, :one_two_games, :integer
	  add_column :seasons, :one_three_ortg, :float
	  add_column :seasons, :one_three_drtg, :float
	  add_column :seasons, :one_three_poss, :float
	  add_column :seasons, :one_three_games, :integer

	  add_column :seasons, :two_zero_ortg, :float
	  add_column :seasons, :two_zero_drtg, :float
	  add_column :seasons, :two_zero_poss, :float
	  add_column :seasons, :two_zero_games, :integer
	  add_column :seasons, :two_one_ortg, :float
	  add_column :seasons, :two_one_drtg, :float
	  add_column :seasons, :two_one_poss, :float
	  add_column :seasons, :two_one_games, :integer
	  add_column :seasons, :two_two_ortg, :float
	  add_column :seasons, :two_two_drtg, :float
	  add_column :seasons, :two_two_poss, :float
	  add_column :seasons, :two_two_games, :integer
	  add_column :seasons, :two_three_ortg, :float
	  add_column :seasons, :two_three_drtg, :float
	  add_column :seasons, :two_three_poss, :float
	  add_column :seasons, :two_three_games, :integer

	  add_column :seasons, :three_zero_ortg, :float
	  add_column :seasons, :three_zero_drtg, :float
	  add_column :seasons, :three_zero_poss, :float
	  add_column :seasons, :three_zero_games, :integer
	  add_column :seasons, :three_one_ortg, :float
	  add_column :seasons, :three_one_drtg, :float
	  add_column :seasons, :three_one_poss, :float
	  add_column :seasons, :three_one_games, :integer
	  add_column :seasons, :three_two_ortg, :float
	  add_column :seasons, :three_two_drtg, :float
	  add_column :seasons, :three_two_poss, :float
	  add_column :seasons, :three_two_games, :integer
	  add_column :seasons, :three_three_ortg, :float
	  add_column :seasons, :three_three_drtg, :float
	  add_column :seasons, :three_three_poss, :float
	  add_column :seasons, :three_three_games, :integer

  end
end